# http://www.appveyor.com/docs/appveyor-yml

# configuration for develop/CI and master/Release branch
-
  branches:
    only:
      - develop
      - master

  skip_tags: true
  image: Visual Studio 2017
  test: off

  pull_requests:
    do_not_increment_build_number: false

  build_script:
    - ps: .\build.ps1

  nuget:
    disable_publish_on_pr: true